'\" t -*- coding: UTF-8 -*-
.\" Copyright 2009   Lefteris Dimitroulakis (edimitro@tee.gr)
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.TH ISO_8859-13 7 2014-10-02 "Linux" "Linux Programmer's Manual"
.SH NAME
iso_8859-13 \- ISO 8859-13 character set encoded in octal, decimal,
and hexadecimal
.SH DESCRIPTION
The ISO 8859 standard includes several 8-bit extensions to the ASCII
character set (also known as ISO 646-IRV).
ISO 8859-13 encodes the
characters used in Baltic Rim languages.
.SS ISO 8859 alphabets
The full set of ISO 8859 alphabets includes:
.TS
l l.
ISO 8859-1	West European languages (Latin-1)
ISO 8859-2	Central and East European languages (Latin-2)
ISO 8859-3	Southeast European and miscellaneous languages (Latin-3)
ISO 8859-4	Scandinavian/Baltic languages (Latin-4)
ISO 8859-5	Latin/Cyrillic
ISO 8859-6	Latin/Arabic
ISO 8859-7	Latin/Greek
ISO 8859-8	Latin/Hebrew
ISO 8859-9	Latin-1 modification for Turkish (Latin-5)
ISO 8859-10	Lappish/Nordic/Eskimo languages (Latin-6)
ISO 8859-11	Latin/Thai
ISO 8859-13	Baltic Rim languages (Latin-7)
ISO 8859-14	Celtic (Latin-8)
ISO 8859-15	West European languages (Latin-9)
ISO 8859-16	Romanian (Latin-10)
.TE
.SS ISO 8859-13 characters
The following table displays the characters in ISO 8859-13, which
are printable and unlisted in the
.BR ascii (7)
manual page.
.TS
l l l c lp-1.
Oct	Dec	Hex	Char	Description
_
240	160	A0	 	NO-BREAK SPACE
241	161	A1	”	RIGHT DOUBLE QUOTATION MARK
242	162	A2	¢	CENT SIGN
243	163	A3	£	POUND SIGN
244	164	A4	¤	CURRENCY SIGN
245	165	A5	„	DOUBLE LOW-9 QUOTATION MARK
246	166	A6	¦	BROKEN BAR
247	167	A7	§	SECTION SIGN
250	168	A8	Ø	LATIN CAPITAL LETTER O WITH STROKE
251	169	A9	©	COPYRIGHT SIGN
252	170	AA	Ŗ	LATIN CAPITAL LETTER R WITH CEDILLA
253	171	AB	«	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
254	172	AC	¬	NOT SIGN
255	173	AD	­	SOFT HYPHEN
256	174	AE	®	REGISTERED SIGN
257	175	AF	Æ	LATIN CAPITAL LETTER AE
260	176	B0	°	DEGREE SIGN
261	177	B1	±	PLUS-MINUS SIGN
262	178	B2	²	SUPERSCRIPT TWO
263	179	B3	³	SUPERSCRIPT THREE
264	180	B4	“	LEFT DOUBLE QUOTATION MARK
265	181	B5	µ	MICRO SIGN
266	182	B6	¶	PILCROW SIGN
267	183	B7	·	MIDDLE DOT
270	184	B8	ø	LATIN SMALL LETTER O WITH STROKE
271	185	B9	¹	SUPERSCRIPT ONE
272	186	BA	ŗ	LATIN SMALL LETTER R WITH CEDILLA
273	187	BB	»	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
274	188	BC	¼	VULGAR FRACTION ONE QUARTER
275	189	BD	½	VULGAR FRACTION ONE HALF
276	190	BE	¾	VULGAR FRACTION THREE QUARTERS
277	191	BF	æ	LATIN SMALL LETTER AE
300	192	C0	Ą	LATIN CAPITAL LETTER A WITH OGONEK
301	193	C1	Į	LATIN CAPITAL LETTER I WITH OGONEK
302	194	C2	Ā	LATIN CAPITAL LETTER A WITH MACRON
303	195	C3	Ć	LATIN CAPITAL LETTER C WITH ACUTE
304	196	C4	Ä	LATIN CAPITAL LETTER A WITH DIAERESIS
305	197	C5	Å	LATIN CAPITAL LETTER A WITH RING ABOVE
306	198	C6	Ę	LATIN CAPITAL LETTER E WITH OGONEK
307	199	C7	Ē	LATIN CAPITAL LETTER E WITH MACRON
310	200	C8	Č	LATIN CAPITAL LETTER C WITH CARON
311	201	C9	É	LATIN CAPITAL LETTER E WITH ACUTE
312	202	CA	Ź	LATIN CAPITAL LETTER Z WITH ACUTE
313	203	CB	Ė	LATIN CAPITAL LETTER E WITH DOT ABOVE
314	204	CC	Ģ	LATIN CAPITAL LETTER G WITH CEDILLA
315	205	CD	Ķ	LATIN CAPITAL LETTER K WITH CEDILLA
316	206	CE	Ī	LATIN CAPITAL LETTER I WITH MACRON
317	207	CF	Ļ	LATIN CAPITAL LETTER L WITH CEDILLA
320	208	D0	Š	LATIN CAPITAL LETTER S WITH CARON
321	209	D1	Ń	LATIN CAPITAL LETTER N WITH ACUTE
322	210	D2	Ņ	LATIN CAPITAL LETTER N WITH CEDILLA
323	211	D3	Ó	LATIN CAPITAL LETTER O WITH ACUTE
324	212	D4	Ō	LATIN CAPITAL LETTER O WITH MACRON
325	213	D5	Õ	LATIN CAPITAL LETTER O WITH TILDE
326	214	D6	Ö	LATIN CAPITAL LETTER O WITH DIAERESIS
327	215	D7	×	MULTIPLICATION SIGN
330	216	D8	Ų	LATIN CAPITAL LETTER U WITH OGONEK
331	217	D9	Ł	LATIN CAPITAL LETTER L WITH STROKE
332	218	DA	Ś	LATIN CAPITAL LETTER S WITH ACUTE
333	219	DB	Ū	LATIN CAPITAL LETTER U WITH MACRON
334	220	DC	Ü	LATIN CAPITAL LETTER U WITH DIAERESIS
335	221	DD	Ż	LATIN CAPITAL LETTER Z WITH DOT ABOVE
336	222	DE	Ž	LATIN CAPITAL LETTER Z WITH CARON
337	223	DF	ß	LATIN SMALL LETTER SHARP S
340	224	E0	ą	LATIN SMALL LETTER A WITH OGONEK
341	225	E1	į	LATIN SMALL LETTER I WITH OGONEK
342	226	E2	ā	LATIN SMALL LETTER A WITH MACRON
343	227	E3	ć	LATIN SMALL LETTER C WITH ACUTE
344	228	E4	ä	LATIN SMALL LETTER A WITH DIAERESIS
345	229	E5	å	LATIN SMALL LETTER A WITH RING ABOVE
346	230	E6	ę	LATIN SMALL LETTER E WITH OGONEK
347	231	E7	ē	LATIN SMALL LETTER E WITH MACRON
350	232	E8	č	LATIN SMALL LETTER C WITH CARON
351	233	E9	é	LATIN SMALL LETTER E WITH ACUTE
352	234	EA	ź	LATIN SMALL LETTER Z WITH ACUTE
353	235	EB	ė	LATIN SMALL LETTER E WITH DOT ABOVE
354	236	EC	ģ	LATIN SMALL LETTER G WITH CEDILLA
355	237	ED	ķ	LATIN SMALL LETTER K WITH CEDILLA
356	238	EE	ī	LATIN SMALL LETTER I WITH MACRON
357	239	EF	ļ	LATIN SMALL LETTER L WITH CEDILLA
360	240	F0	š	LATIN SMALL LETTER S WITH CARON
361	241	F1	ń	LATIN SMALL LETTER N WITH ACUTE
362	242	F2	ņ	LATIN SMALL LETTER N WITH CEDILLA
363	243	F3	ó	LATIN SMALL LETTER O WITH ACUTE
364	244	F4	ō	LATIN SMALL LETTER O WITH MACRON
365	245	F5	õ	LATIN SMALL LETTER O WITH TILDE
366	246	F6	ö	LATIN SMALL LETTER O WITH DIAERESIS
367	247	F7	÷	DIVISION SIGN
370	248	F8	ų	LATIN SMALL LETTER U WITH OGONEK
371	249	F9	ł	LATIN SMALL LETTER L WITH STROKE
372	250	FA	ś	LATIN SMALL LETTER S WITH ACUTE
373	251	FB	ū	LATIN SMALL LETTER U WITH MACRON
374	252	FC	ü	LATIN SMALL LETTER U WITH DIAERESIS
375	253	FD	ż	LATIN SMALL LETTER Z WITH DOT ABOVE
376	254	FE	ž	LATIN SMALL LETTER Z WITH CARON
377	255	FF	’	RIGHT SINGLE QUOTATION MARK
.TE
.SH NOTES
ISO 8859-13 is also known as Latin-7.
.SH SEE ALSO
.BR ascii (7),
.BR charsets (7),
.BR utf-8 (7)
