'\" t -*- coding: UTF-8 -*-
.\" Copyright 2009   Lefteris Dimitroulakis (edimitro@tee.gr)
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.TH ISO_8859-5 7 2014-10-02 "Linux" "Linux Programmer's Manual"
.SH NAME
iso_8859-5 \- ISO 8859-5 character set encoded in octal, decimal,
and hexadecimal
.SH DESCRIPTION
The ISO 8859 standard includes several 8-bit extensions to the ASCII
character set (also known as ISO 646-IRV).
ISO 8859-5 encodes the
Cyrillic characters used in many East European languages.
.SS ISO 8859 alphabets
The full set of ISO 8859 alphabets includes:
.TS
l l.
ISO 8859-1	West European languages (Latin-1)
ISO 8859-2	Central and East European languages (Latin-2)
ISO 8859-3	Southeast European and miscellaneous languages (Latin-3)
ISO 8859-4	Scandinavian/Baltic languages (Latin-4)
ISO 8859-5	Latin/Cyrillic
ISO 8859-6	Latin/Arabic
ISO 8859-7	Latin/Greek
ISO 8859-8	Latin/Hebrew
ISO 8859-9	Latin-1 modification for Turkish (Latin-5)
ISO 8859-10	Lappish/Nordic/Eskimo languages (Latin-6)
ISO 8859-11	Latin/Thai
ISO 8859-13	Baltic Rim languages (Latin-7)
ISO 8859-14	Celtic (Latin-8)
ISO 8859-15	West European languages (Latin-9)
ISO 8859-16	Romanian (Latin-10)
.TE
.SS ISO 8859-5 characters
The following table displays the characters in ISO 8859-5, which
are printable and unlisted in the
.BR ascii (7)
manual page.
.TS
l l l c lp-1.
Oct	Dec	Hex	Char	Description
_
240	160	A0	 	NO-BREAK SPACE
241	161	A1	Ё	CYRILLIC CAPITAL LETTER IO
242	162	A2	Ђ	CYRILLIC CAPITAL LETTER DJE
243	163	A3	Ѓ	CYRILLIC CAPITAL LETTER GJE
244	164	A4	Є	CYRILLIC CAPITAL LETTER UKRAINIAN IE
245	165	A5	Ѕ	CYRILLIC CAPITAL LETTER DZE
246	166	A6	І	T{
CYRILLIC CAPITAL LETTER
.br
BYELORUSSIAN-UKRAINIAN I
T}
247	167	A7	Ї	CYRILLIC CAPITAL LETTER YI
250	168	A8	Ј	CYRILLIC CAPITAL LETTER JE
251	169	A9	Љ	CYRILLIC CAPITAL LETTER LJE
252	170	AA	Њ	CYRILLIC CAPITAL LETTER NJE
253	171	AB	Ћ	CYRILLIC CAPITAL LETTER TSHE
254	172	AC	Ќ	CYRILLIC CAPITAL LETTER KJE
255	173	AD	­	SOFT HYPHEN
256	174	AE	Ў	CYRILLIC CAPITAL LETTER SHORT U
257	175	AF	Џ	CYRILLIC CAPITAL LETTER DZHE
260	176	B0	А	CYRILLIC CAPITAL LETTER A
261	177	B1	Б	CYRILLIC CAPITAL LETTER BE
262	178	B2	В	CYRILLIC CAPITAL LETTER VE
263	179	B3	Г	CYRILLIC CAPITAL LETTER GHE
264	180	B4	Д	CYRILLIC CAPITAL LETTER DE
265	181	B5	Е	CYRILLIC CAPITAL LETTER IE
266	182	B6	Ж	CYRILLIC CAPITAL LETTER ZHE
267	183	B7	З	CYRILLIC CAPITAL LETTER ZE
270	184	B8	И	CYRILLIC CAPITAL LETTER I
271	185	B9	Й	CYRILLIC CAPITAL LETTER SHORT I
272	186	BA	К	CYRILLIC CAPITAL LETTER KA
273	187	BB	Л	CYRILLIC CAPITAL LETTER EL
274	188	BC	М	CYRILLIC CAPITAL LETTER EM
275	189	BD	Н	CYRILLIC CAPITAL LETTER EN
276	190	BE	О	CYRILLIC CAPITAL LETTER O
277	191	BF	П	CYRILLIC CAPITAL LETTER PE
300	192	C0	Р	CYRILLIC CAPITAL LETTER ER
301	193	C1	С	CYRILLIC CAPITAL LETTER ES
302	194	C2	Т	CYRILLIC CAPITAL LETTER TE
303	195	C3	У	CYRILLIC CAPITAL LETTER U
304	196	C4	Ф	CYRILLIC CAPITAL LETTER EF
305	197	C5	Х	CYRILLIC CAPITAL LETTER HA
306	198	C6	Ц	CYRILLIC CAPITAL LETTER TSE
307	199	C7	Ч	CYRILLIC CAPITAL LETTER CHE
310	200	C8	Ш	CYRILLIC CAPITAL LETTER SHA
311	201	C9	Щ	CYRILLIC CAPITAL LETTER SHCHA
312	202	CA	Ъ	CYRILLIC CAPITAL LETTER HARD SIGN
313	203	CB	Ы	CYRILLIC CAPITAL LETTER YERU
314	204	CC	Ь	CYRILLIC CAPITAL LETTER SOFT SIGN
315	205	CD	Э	CYRILLIC CAPITAL LETTER E
316	206	CE	Ю	CYRILLIC CAPITAL LETTER YU
317	207	CF	Я	CYRILLIC CAPITAL LETTER YA
320	208	D0	а	CYRILLIC SMALL LETTER A
321	209	D1	б	CYRILLIC SMALL LETTER BE
322	210	D2	в	CYRILLIC SMALL LETTER VE
323	211	D3	г	CYRILLIC SMALL LETTER GHE
324	212	D4	д	CYRILLIC SMALL LETTER DE
325	213	D5	е	CYRILLIC SMALL LETTER IE
326	214	D6	ж	CYRILLIC SMALL LETTER ZHE
327	215	D7	з	CYRILLIC SMALL LETTER ZE
330	216	D8	и	CYRILLIC SMALL LETTER I
331	217	D9	й	CYRILLIC SMALL LETTER SHORT I
332	218	DA	к	CYRILLIC SMALL LETTER KA
333	219	DB	л	CYRILLIC SMALL LETTER EL
334	220	DC	м	CYRILLIC SMALL LETTER EM
335	221	DD	н	CYRILLIC SMALL LETTER EN
336	222	DE	о	CYRILLIC SMALL LETTER O
337	223	DF	п	CYRILLIC SMALL LETTER PE
340	224	E0	р	CYRILLIC SMALL LETTER ER
341	225	E1	с	CYRILLIC SMALL LETTER ES
342	226	E2	т	CYRILLIC SMALL LETTER TE
343	227	E3	у	CYRILLIC SMALL LETTER U
344	228	E4	ф	CYRILLIC SMALL LETTER EF
345	229	E5	х	CYRILLIC SMALL LETTER HA
346	230	E6	ц	CYRILLIC SMALL LETTER TSE
347	231	E7	ч	CYRILLIC SMALL LETTER CHE
350	232	E8	ш	CYRILLIC SMALL LETTER SHA
351	233	E9	щ	CYRILLIC SMALL LETTER SHCHA
352	234	EA	ъ	CYRILLIC SMALL LETTER HARD SIGN
353	235	EB	ы	CYRILLIC SMALL LETTER YERU
354	236	EC	ь	CYRILLIC SMALL LETTER SOFT SIGN
355	237	ED	э	CYRILLIC SMALL LETTER E
356	238	EE	ю	CYRILLIC SMALL LETTER YU
357	239	EF	я	CYRILLIC SMALL LETTER YA
360	240	F0	№	NUMERO SIGN
361	241	F1	ё	CYRILLIC SMALL LETTER IO
362	242	F2	ђ	CYRILLIC SMALL LETTER DJE
363	243	F3	ѓ	CYRILLIC SMALL LETTER GJE
364	244	F4	є	CYRILLIC SMALL LETTER UKRAINIAN IE
365	245	F5	ѕ	CYRILLIC SMALL LETTER DZE
366	246	F6	і	CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
367	247	F7	ї	CYRILLIC SMALL LETTER YI
370	248	F8	ј	CYRILLIC SMALL LETTER JE
371	249	F9	љ	CYRILLIC SMALL LETTER LJE
372	250	FA	њ	CYRILLIC SMALL LETTER NJE
373	251	FB	ј	CYRILLIC SMALL LETTER TSHE
374	252	FC	ќ	CYRILLIC SMALL LETTER KJE
375	253	FD	§	SECTION SIGN
376	254	FE	ў	CYRILLIC SMALL LETTER SHORT U
377	255	FF	џ	CYRILLIC SMALL LETTER DZHE
.TE
.SH SEE ALSO
.BR ascii (7),
.BR charsets (7),
.BR koi8-r (7),
.BR koi8-u (7),
.BR utf-8 (7)
