'\" t -*- coding: UTF-8 -*-
.\" Copyright 2009  Lefteris Dimitroulakis <edimitro at tee.gr>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_FULL)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, see
.\" <http://www.gnu.org/licenses/>.
.\" %%%LICENSE_END
.\"
.\" 2009-01-15, mtk, Some edits
.\"
.TH KOI8-U 7 2014-10-02 "Linux" "Linux Programmer's Manual"
.SH NAME
koi8-u \- Ukrainian character set encoded in octal, decimal,
and hexadecimal
.SH DESCRIPTION
RFC\ 2310 defines an 8-bit character set, KOI8-U.
KOI8-U encodes the
characters used in Ukrainian and Byelorussian.
.SS KOI8-U characters
The following table displays the characters in KOI8-U, which
are printable and unlisted in the
.BR ascii (7)
manual page.
.TS
l l l c lp-1.
Oct	Dec	Hex	Char	Description
_
200	128	80	─	BOX DRAWINGS LIGHT HORIZONTAL
201	129	81	│	BOX DRAWINGS LIGHT VERTICAL
202	130	82	┌	BOX DRAWINGS LIGHT DOWN AND RIGHT
203	131	83	┐	BOX DRAWINGS LIGHT DOWN AND LEFT
204	132	84	└	BOX DRAWINGS LIGHT UP AND RIGHT
205	133	85	┘	BOX DRAWINGS LIGHT UP AND LEFT
206	134	86	├	BOX DRAWINGS LIGHT VERTICAL AND RIGHT
207	135	87	┤	BOX DRAWINGS LIGHT VERTICAL AND LEFT
210	136	88	┬	BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
211	137	89	┴	BOX DRAWINGS LIGHT UP AND HORIZONTAL
212	138	8A	┼	BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
213	139	8B	▀	UPPER HALF BLOCK
214	140	8C	▄	LOWER HALF BLOCK
215	141	8D	█	FULL BLOCK
216	142	8E	▌	LEFT HALF BLOCK
217	143	8F	▐	RIGHT HALF BLOCK
220	144	90	░	LIGHT SHADE
221	145	91	▒	MEDIUM SHADE
222	146	92	▓	DARK SHADE
223	147	93	⌠	TOP HALF INTEGRAL
224	148	94	■	BLACK SQUARE
225	149	95	∙	BULLET OPERATOR
226	150	96	√	SQUARE ROOT
227	151	97	≈	ALMOST EQUAL TO
230	152	98	≤	LESS-THAN OR EQUAL TO
231	153	99	≥	GREATER-THAN OR EQUAL TO
232	154	9A	 	NO-BREAK SPACE
233	155	9B	⌡	BOTTOM HALF INTEGRAL
234	156	9C	°	DEGREE SIGN
235	157	9D	²	SUPERSCRIPT TWO
236	158	9E	·	MIDDLE DOT
237	159	9F	÷	DIVISION SIGN
240	160	A0	═	BOX DRAWINGS DOUBLE HORIZONTAL
241	161	A1	║	BOX DRAWINGS DOUBLE VERTICAL
242	162	A2	╒	BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
243	163	A3	ё	CYRILLIC SMALL LETTER IO
244	164	A4	є	CYRILLIC SMALL LETTER UKRAINIAN IE
245	165	A5	╔	BOX DRAWINGS DOUBLE DOWN AND RIGHT
246	166	A6	і	T{
CYRILLIC SMALL LETTER
.br
BYELORUSSIAN-UKRAINIAN I
T}
247	167	A7	ї	CYRILLIC SMALL LETTER YI (Ukrainian)
250	168	A8	╗	BOX DRAWINGS DOUBLE DOWN AND LEFT
251	169	A9	╘	BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
252	170	AA	╙	BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
253	171	AB	╚	BOX DRAWINGS DOUBLE UP AND RIGHT
254	172	AC	╛	BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
255	173	AD	ґ	CYRILLIC SMALL LETTER GHE WITH UPTURN
256	174	AE	╝	BOX DRAWINGS DOUBLE UP AND LEFT
257	175	AF	╞	BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
260	176	B0	╟	BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
261	177	B1	╠	BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
262	178	B2	╡	BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
263	179	B3	Ё	CYRILLIC CAPITAL LETTER IO
264	180	B4	Є	CYRILLIC CAPITAL LETTER UKRAINIAN IE
265	181	B5	╣	BOX DRAWINGS DOUBLE VERTICAL AND LEFT
266	182	B6	І	T{
CYRILLIC CAPITAL LETTER
.br
BYELORUSSIAN-UKRAINIAN I
T}
267	183	B7	Ї	CYRILLIC CAPITAL LETTER YI (Ukrainian)
270	184	B8	╦	BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
271	185	B9	╧	BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
272	186	BA	╨	BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
273	187	BB	╩	BOX DRAWINGS DOUBLE UP AND HORIZONTAL
274	188	BC	╪	T{
BOX DRAWINGS VERTICAL SINGLE
.br
AND HORIZONTAL DOUBLE
T}
275	189	BD	Ґ	CYRILLIC CAPITAL LETTER GHE WITH UPTURN
276	190	BE	╬	BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
277	191	BF	©	COPYRIGHT SIGN
300	192	C0	ю	CYRILLIC SMALL LETTER YU
301	193	C1	а	CYRILLIC SMALL LETTER A
302	194	C2	б	CYRILLIC SMALL LETTER BE
303	195	C3	ц	CYRILLIC SMALL LETTER TSE
304	196	C4	д	CYRILLIC SMALL LETTER DE
305	197	C5	е	CYRILLIC SMALL LETTER IE
306	198	C6	ф	CYRILLIC SMALL LETTER EF
307	199	C7	г	CYRILLIC SMALL LETTER GHE
310	200	C8	х	CYRILLIC SMALL LETTER HA
311	201	C9	и	CYRILLIC SMALL LETTER I
312	202	CA	й	CYRILLIC SMALL LETTER SHORT I
313	203	CB	к	CYRILLIC SMALL LETTER KA
314	204	CC	л	CYRILLIC SMALL LETTER EL
315	205	CD	м	CYRILLIC SMALL LETTER EM
316	206	CE	н	CYRILLIC SMALL LETTER EN
317	207	CF	о	CYRILLIC SMALL LETTER O
320	208	D0	п	CYRILLIC SMALL LETTER PE
321	209	D1	я	CYRILLIC SMALL LETTER YA
322	210	D2	р	CYRILLIC SMALL LETTER ER
323	211	D3	с	CYRILLIC SMALL LETTER ES
324	212	D4	т	CYRILLIC SMALL LETTER TE
325	213	D5	у	CYRILLIC SMALL LETTER U
326	214	D6	ж	CYRILLIC SMALL LETTER ZHE
327	215	D7	в	CYRILLIC SMALL LETTER VE
330	216	D8	ь	CYRILLIC SMALL LETTER SOFT SIGN
331	217	D9	ы	CYRILLIC SMALL LETTER YERU
332	218	DA	з	CYRILLIC SMALL LETTER ZE
333	219	DB	ш	CYRILLIC SMALL LETTER SHA
334	220	DC	э	CYRILLIC SMALL LETTER E
335	221	DD	щ	CYRILLIC SMALL LETTER SHCHA
336	222	DE	ч	CYRILLIC SMALL LETTER CHE
337	223	DF	ъ	CYRILLIC SMALL LETTER HARD SIGN
340	224	E0	Ю	CYRILLIC CAPITAL LETTER YU
341	225	E1	А	CYRILLIC CAPITAL LETTER A
342	226	E2	Б	CYRILLIC CAPITAL LETTER BE
343	227	E3	Ц	CYRILLIC CAPITAL LETTER TSE
344	228	E4	Д	CYRILLIC CAPITAL LETTER DE
345	229	E5	Е	CYRILLIC CAPITAL LETTER IE
346	230	E6	Ф	CYRILLIC CAPITAL LETTER EF
347	231	E7	Г	CYRILLIC CAPITAL LETTER GHE
350	232	E8	Х	CYRILLIC CAPITAL LETTER HA
351	233	E9	И	CYRILLIC CAPITAL LETTER I
352	234	EA	Й	CYRILLIC CAPITAL LETTER SHORT I
353	235	EB	К	CYRILLIC CAPITAL LETTER KA
354	236	EC	Л	CYRILLIC CAPITAL LETTER EL
355	237	ED	М	CYRILLIC CAPITAL LETTER EM
356	238	EE	Н	CYRILLIC CAPITAL LETTER EN
357	239	EF	О	CYRILLIC CAPITAL LETTER O
360	240	F0	П	CYRILLIC CAPITAL LETTER PE
361	241	F1	Я	CYRILLIC CAPITAL LETTER YA
362	242	F2	Р	CYRILLIC CAPITAL LETTER ER
363	243	F3	С	CYRILLIC CAPITAL LETTER ES
364	244	F4	Т	CYRILLIC CAPITAL LETTER TE
365	245	F5	У	CYRILLIC CAPITAL LETTER U
366	246	F6	Ж	CYRILLIC CAPITAL LETTER ZHE
367	247	F7	В	CYRILLIC CAPITAL LETTER VE
370	248	F8	Ь	CYRILLIC CAPITAL LETTER SOFT SIGN
371	249	F9	Ы	CYRILLIC CAPITAL LETTER YERU
372	250	FA	З	CYRILLIC CAPITAL LETTER ZE
373	251	FB	Ш	CYRILLIC CAPITAL LETTER SHA
374	252	FC	Э	CYRILLIC CAPITAL LETTER E
375	253	FD	Щ	CYRILLIC CAPITAL LETTER SHCHA
376	254	FE	Ч	CYRILLIC CAPITAL LETTER CHE
377	255	FF	Ъ	CYRILLIC CAPITAL LETTER HARD SIGN
.TE
.SH NOTES
The differences from KOI8-R are in the hex positions
A4, A6, A7, AD, B4, B6, B7, and BD.
.SH SEE ALSO
.BR ascii (7),
.BR charsets (7),
.BR iso_8859-5 (7),
.BR koi8-r (7),
.BR utf-8 (7)
