.\" Copyright (c) 1994 Andries Brouwer (aeb@cwi.nl), Mon Oct 31 21:03:19 MET 1994
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_ONEPARA)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\" %%%LICENSE_END
.\"
.\" Modified, Sun Feb 26 14:58:45 1995, faith@cs.unc.edu
.\" "
.TH CONSOLE 4 1994-10-31 "Linux" "Linux Programmer's Manual"
.SH NAME
console \- console terminal and virtual consoles
.SH DESCRIPTION
A Linux system has up to 63
.I "virtual consoles"
(character devices with major number 4 and minor number 1 to 63),
usually called
.I /dev/ttyn
with 1 \(<=
.I n
\(<= 63.
The current console is also addressed by
.I /dev/console
or
.IR /dev/tty0 ,
the character device with
major number 4 and minor number 0.
The device files
.I /dev/*
are usually created using the script MAKEDEV,
or using
.BR mknod (1),
usually with mode 0622 and owner
.IR root.tty .
.LP
Before kernel version 1.1.54 the number of virtual consoles was
compiled into the kernel (in
.IR tty.h :
#define NR_CONSOLES 8)
and could be changed by editing and recompiling.
Since version 1.1.54 virtual consoles are created on the fly,
as soon as they are needed.
.LP
Common ways to start a process on a console are:
(a) tell
.BR init (1)
(in
.BR inittab (5))
to start a
.BR mingetty (8)
(or
.BR agetty (8))
on the console;
(b) ask
.BR openvt (1)
to start a process on the console;
(c) start X\(emit will find the first unused console,
and display its output there.
(There is also the ancient
.BR doshell (8).)
.LP
Common ways to switch consoles are: (a) use Alt+F\fIn\fP or
Ctrl+Alt+F\fIn\fP to switch to console
.IR n ;
AltGr+F\fIn\fP
might bring you to console \fIn\fP+12 [here Alt and AltGr refer
to the left and right Alt keys, respectively];
(b) use Alt+RightArrow or Alt+LeftArrow to cycle through
the presently allocated consoles; (c) use the program
.BR chvt (1).
(The key mapping is user settable, see
.BR loadkeys (1);
the above mentioned key combinations are according to the default settings.)
.LP
The command
.BR deallocvt (1)
(formerly
.BR disalloc )
will free the memory taken by the screen buffers for consoles
that no longer have any associated process.
.SS Properties
Consoles carry a lot of state.
I hope to document that some other time.
The most important fact is that the consoles simulate vt100 terminals.
In particular, a console is reset to the initial state by printing the two
characters ESC c.
All escape sequences can be found in
.BR console_codes (4).
.SH FILES
.I /dev/console
.br
.I /dev/tty*
.SH SEE ALSO
.BR chvt (1),
.BR deallocvt (1),
.BR init (1),
.BR loadkeys (1),
.BR mknod (1),
.BR openvt (1),
.BR console_codes (4),
.BR console_ioctl (4),
.BR tty (4),
.BR ttyS (4),
.BR charsets (7),
.BR agetty (8),
.BR mapscrn (8),
.BR mingetty (8),
.BR resizecons (8),
.BR setfont (8)
