.\" Copyright (c) 2002 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.TH SIGWAITINFO 2 2015-07-23 "Linux" "Linux Programmer's Manual"
.SH NAME
sigwaitinfo, sigtimedwait, rt_sigtimedwait \- synchronously wait
for queued signals
.SH SYNOPSIS
.nf
.B #include <signal.h>
.sp
.BI "int sigwaitinfo(const sigset_t *" set ", siginfo_t *" info ");"
.sp
.BI "int sigtimedwait(const sigset_t *" set ", siginfo_t *" info ", "
.BI "                 const struct timespec *" timeout ");"
.fi
.sp
.in -4n
Feature Test Macro Requirements for glibc (see
.BR feature_test_macros (7)):
.in
.sp
.BR sigwaitinfo (),
.BR sigtimedwait ():
_POSIX_C_SOURCE\ >=\ 199309L
.SH DESCRIPTION
.BR sigwaitinfo ()
suspends execution of the calling thread until one of the signals in
.I set
is pending
(If one of the signals in
.I set
is already pending for the calling thread,
.BR sigwaitinfo ()
will return immediately.)

.BR sigwaitinfo ()
removes the signal from the set of pending
signals and returns the signal number as its function result.
If the
.I info
argument is not NULL,
then the buffer that it points to is used to return a structure of type
.I siginfo_t
(see
.BR sigaction (2))
containing information about the signal.
.PP
If multiple signals in
.I set
are pending for the caller, the signal that is retrieved by
.BR sigwaitinfo ()
is determined according to the usual ordering rules; see
.BR signal (7)
for further details.
.PP
.BR sigtimedwait ()
operates in exactly the same way as
.BR sigwaitinfo ()
except that it has an additional argument,
.IR timeout ,
which specifies the interval for which
the thread is suspended waiting for a signal.
(This interval will be rounded up to the system clock granularity,
and kernel scheduling delays mean that the interval
may overrun by a small amount.)
This argument is of the following type:
.sp
.in +4n
.nf
struct timespec {
    long    tv_sec;         /* seconds */
    long    tv_nsec;        /* nanoseconds */
}
.fi
.in
.sp
If both fields of this structure are specified as 0, a poll is performed:
.BR sigtimedwait ()
returns immediately, either with information about a signal that
was pending for the caller, or with an error
if none of the signals in
.I set
was pending.
.SH RETURN VALUE
On success, both
.BR sigwaitinfo ()
and
.BR sigtimedwait ()
return a signal number (i.e., a value greater than zero).
On failure both calls return \-1, with
.I errno
set to indicate the error.
.SH ERRORS
.TP
.B EAGAIN
No signal in
.I set
was became pending within the
.I timeout
period specified to
.BR sigtimedwait ().
.TP
.B EINTR
The wait was interrupted by a signal handler; see
.BR signal (7).
(This handler was for a signal other than one of those in
.IR set .)
.TP
.B EINVAL
.I timeout
was invalid.
.SH CONFORMING TO
POSIX.1-2001, POSIX.1-2008.
.SH NOTES
In normal usage, the calling program blocks the signals in
.I set
via a prior call to
.BR sigprocmask (2)
(so that the default disposition for these signals does not occur if they
become pending between successive calls to
.BR sigwaitinfo ()
or
.BR sigtimedwait ())
and does not establish handlers for these signals.
In a multithreaded program,
the signal should be blocked in all threads, in order to prevent
the signal being treated according to its default disposition in
a thread other than the one calling
.BR sigwaitinfo ()
or
.BR sigtimedwait ()).

The set of signals that is pending for a given thread is the
union of the set of signals that is pending specifically for that thread
and the set of signals that is pending for the process as a whole (see
.BR signal (7)).

Attempts to wait for
.B SIGKILL
and
.B SIGSTOP
are silently ignored.

If multiple threads of a process are blocked
waiting for the same signal(s) in
.BR sigwaitinfo ()
or
.BR sigtimedwait (),
then exactly one of the threads will actually receive the
signal if it becomes pending for the process as a whole;
which of the threads receives the signal is indeterminate.

POSIX leaves the meaning of a NULL value for the
.I timeout
argument of
.BR sigtimedwait ()
unspecified, permitting the possibility that this has the same meaning
as a call to
.BR sigwaitinfo (),
and indeed this is what is done on Linux.
.\"
.SS C library/kernel differences
On Linux,
.BR sigwaitinfo ()
is a library function implemented on top of
.BR sigtimedwait ().

The glibc wrapper functions for
.BR sigwaitinfo ()
and
.BR sigtimedwait ()
silently ignore attempts to wait for the two real-time signals that
are used internally by the NPTL threading implementation.
See
.BR nptl (7)
for details.

The original Linux system call was named
.BR sigtimedwait ().
However, with the addition of real-time signals in Linux 2.2,
the fixed-size, 32-bit
.I sigset_t
type supported by that system call was no longer fit for purpose.
Consequently, a new system call,
.BR rt_sigtimedwait (),
was added to support an enlarged
.IR sigset_t
type.
The new system call takes a fourth argument,
.IR "size_t sigsetsize" ,
which specifies the size in bytes of the signal set in
.IR set .
This argument is currently required to have the value
.IR sizeof(sigset_t)
(or the error
.B EINVAL
results).
The glibc
.BR sigtimedwait ()
wrapper function hides these details from us, transparently calling
.BR rt_sigtimedwait ()
when the kernel provides it.
.\"
.SH SEE ALSO
.BR kill (2),
.BR sigaction (2),
.BR signal (2),
.BR signalfd (2),
.BR sigpending (2),
.BR sigprocmask (2),
.BR sigqueue (3),
.BR sigsetops (3),
.BR sigwait (3),
.BR signal (7),
.BR time (7)
