.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_ONEPARA)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"
.TH WCPCPY 3  2015-03-02 "GNU" "Linux Programmer's Manual"
.SH NAME
wcpcpy \- copy a wide-character string, returning a pointer to its end
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcpcpy(wchar_t *" dest ", const wchar_t *" src );
.fi
.sp
.in -4n
Feature Test Macro Requirements for glibc (see
.BR feature_test_macros (7)):
.in
.sp
.BR wcpcpy ():
.PD 0
.ad l
.RS 4
.TP 4
Since glibc 2.10:
_XOPEN_SOURCE\ >=\ 700 || _POSIX_C_SOURCE\ >=\ 200809L
.TP
Before glibc 2.10:
_GNU_SOURCE
.RE
.ad
.PD
.SH DESCRIPTION
The
.BR wcpcpy ()
function is the wide-character equivalent of the
.BR stpcpy (3)
function.
It copies the wide-character string pointed to by
.IR src ,
including the terminating null wide character (L\(aq\\0\(aq),
to the array pointed to by
.IR dest .
.PP
The strings may not overlap.
.PP
The programmer must ensure that there
is room for at least
.IR wcslen(src)+1
wide characters at
.IR dest .
.SH RETURN VALUE
.BR wcpcpy ()
returns a pointer to the end of the wide-character string
.IR dest ,
that is, a pointer to the terminating null wide character.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR wcpcpy ()
T}	Thread safety	MT-Safe
.TE
.SH CONFORMING TO
POSIX.1-2008.
.SH SEE ALSO
.BR strcpy (3),
.BR wcscpy (3)
