.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_ONEPARA)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.TH WCSPBRK 3  2015-08-08 "GNU" "Linux Programmer's Manual"
.SH NAME
wcspbrk \- search a wide-character string for any of a set of wide characters
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wcspbrk(const wchar_t *" wcs ", const wchar_t *" accept );
.fi
.SH DESCRIPTION
The
.BR wcspbrk ()
function is the wide-character equivalent
of the
.BR strpbrk (3)
function.
It searches for the first occurrence in the wide-character
string pointed to by
.I wcs
of any of the
characters in the wide-character
string pointed to by
.IR accept .
.SH RETURN VALUE
The
.BR wcspbrk ()
function returns a pointer to the first occurrence in
.I wcs
of any of the characters listed in
.IR accept .
If
.I wcs
contains none of these characters, NULL is returned.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR wcspbrk ()
T}	Thread safety	MT-Safe
.TE
.SH CONFORMING TO
POSIX.1-2001, POSIX.1-2008, C99.
.SH SEE ALSO
.BR strpbrk (3),
.BR wcschr (3),
.BR wcscspn (3)
