.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" %%%LICENSE_START(GPLv2+_DOC_ONEPARA)
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.TH WMEMCPY 3  2015-08-08 "GNU" "Linux Programmer's Manual"
.SH NAME
wmemcpy \- copy an array of wide-characters
.SH SYNOPSIS
.nf
.B #include <wchar.h>
.sp
.BI "wchar_t *wmemcpy(wchar_t *" dest ", const wchar_t *" src ", size_t " n );
.fi
.SH DESCRIPTION
The
.BR wmemcpy ()
function is the wide-character equivalent of the
.BR memcpy (3)
function.
It copies
.I n
wide characters from the array starting at
.I src
to the array starting at
.IR dest .
.PP
The arrays may not overlap; use
.BR wmemmove (3)
to copy between overlapping
arrays.
.PP
The programmer must ensure that there is room for at least
.I n
wide
characters at
.IR dest .
.SH RETURN VALUE
.BR wmemcpy ()
returns
.IR dest .
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lb lb lb
l l l.
Interface	Attribute	Value
T{
.BR wmemcpy ()
T}	Thread safety	MT-Safe
.TE
.SH CONFORMING TO
POSIX.1-2001, POSIX.1-2008, C99.
.SH SEE ALSO
.BR memcpy (3),
.BR wcscpy (3),
.BR wmemmove (3),
.BR wmempcpy (3)
